### ISSUE TITLE
Area: API

### ISSUE THREAD

**Issue by scragly** [PythonistaGuild/MystBin#1]
This is a tracking ticket to track tasks for initial development of the API, and to discuss the API in a wider scope than what may suit the individual tickets.

TO DO:
- [x] Decide on appropriate API framework.
- [x] Decide on API routes and payload structures.
- [x] Decide on storage method.

API development will be headed by Tomahawk and @AbstractUmbra

**Comment by AbstractUmbra** [comment]
Progress going well. Basic API w/ database infra in place. Will soon flesh out more methods and documentation of internals.
