### ISSUE TITLE
Area: Frontend

### ISSUE THREAD

**Issue by scragly** [PythonistaGuild/MystBin#2]
This is a tracking ticket to track tasks for the initial development of the web frontend and to discuss the site interface in a wider scope than what may suit the individual tickets.

## TO-DO
- [x] Decide on appropriate frontend stack.
- [x] Roughly outline wanted interface and feature set.

## Stack
- Use NextJS (+ React)
     - Server-rendered pastes!
- https://github.com/react-syntax-highlighter/react-syntax-highlighter to make life easier
- Font will change from Font Awesome to [TBD]

##  Feature set
- Instead of a floating navbar, it will be static, with content stacked below it
    - which should fix line number anchors gracefully (no need for the custom event)
    - will probably need a custom scrollbar for the content to look good (scrollbar is now element-bound)
- Two navbars 
    1. The main navbar with logo, `[new]`, `[edit]`, `[delete]`, `[share]`, far-right `[login]`
    2. Second navbar which is used for new and edit, showing `{language}`, `{syntax}`, `{expiry}`
- Footer
     - terms, privacy, cookie on the left
     - copyright, patreon link in middle
     - discord/GitHub logos and OSS license on right
     - contemplating on ethical ads on right

Frontend development will be headed by @EvieePy.

**Comment by EvieePy** [comment]
Idea:

**Context Menus:**

- Line Numbers (for easily highlighting lines and sections)

- Admin
  - Delete Paste
  - Dashboard to quickly delete pastes/ban or upgrade users/regen user token

- Dashboard
  - Delete Paste

This is not a definitive list and is welcome to ideas.

**Comment by EvieePy** [comment]
Use **Material Icons Font** for icons, instead of Font Awesome.
https://material.io/

**Comment by EvieePy** [comment]
**Admin Dashboard**

The admin dashboard will serve as useful tool for site administration.

The admin dashboard should be broken down into the following sections:

- Analytics 

- Pastes (All pastes)
  - Search Bar
  - Context Menu
  - All paste metadata

- Users
  - Search Bar
  - Context Menu
  - User Paste statistics

This is not a definitive list and is open to ideas.
