### ISSUE TITLE
The website sometimes fails to load properly

### ISSUE THREAD

**Issue by parafoxia** [PythonistaGuild/MystBin#30]
The attached screenshot shows how the website has been loading sometimes recently -- I say "sometimes" because this behaviour occurs somewhat at random as far as I can tell.

Idk if it makes a difference, but all the times this has happened have been when loading pastes created using the API -- I don't use Mystbin outside of that, so I don't know if the problem occurs when creating pastes in the browser as well.

I'm also having issues getting any pastes to load on mobile at all. A screenshot of this will be provided in a comment.

![image](https://user-images.githubusercontent.com/43846948/192613496-d00697c7-9132-4bc9-ace4-b1a4ae04add6.png)

**Comment by parafoxia** [comment]
Here's the mobile screenshot.

![Screenshot_20220927-200544.png](https://user-images.githubusercontent.com/43846948/192614023-6fe2c73e-322a-4e40-99d0-6b45e83de639.png)

**Comment by IAmTomahawkx** [comment]
The desktop load issue is a known issue on Firefox. As for mobile, please provide information (os, browser, browser version)

**Comment by parafoxia** [comment]
Android, Firefox, v107.0a1. I am on Nightly but I'm willing to bet the problem exists on stable too.

**Comment by IAmTomahawkx** [comment]
We believe to have fixed this issue in our latest release.

**Comment by parafoxia** [comment]
Yeah, seems to be working well for me now. Thanks!
