### ISSUE TITLE
Automatically Invalidating Discord Tokens

### ISSUE THREAD

**Issue by gfdsohgdkoshgiodsbblbngsal** [PythonistaGuild/MystBin#35]
[Apparently](https://github.com/PythonistaGuild/MystBin#setting-up-apps:~:text=You%20may%20set%20up%20the%20github%20bot%20token%20with%20a%20github%20personal%20access%20token%20to%20enable%20automatic%20invalidation%20of%20discord%20tokens%20(via%20posting%20them%20in%20gists).) MystBin already invalidates Discord Tokens in files, but this is not the case in practice.

I did this in a fresh file, `file.txt`, and pasted a valid discord token. After waiting for a while, nothing happened. No message from discord saying they detected my bot's token out on the internet, nothing. 

[The aforementioned file](https://mystb.in/ConspiracyForestsGrenada)

(the token in there has been invalidated already, don't even try)

**Comment by annoyingdumbas** [comment]
Doesn't work in a .py file either, so the file extension is not the issue

https://mystb.in/DrawMsieLending
