### ISSUE TITLE
Scrolling down with the middle mouse button doesn't work on Firefox.

### ISSUE THREAD

**Issue by itswilliboy** [PythonistaGuild/MystBin#52]
When trying to scroll down with the middle mouse button on a paste that has one line that needs horizontal scrolling, it only allows you to scroll horizontally when using the middle mouse button.

On Edge it works, and the cursor has four arrows when clicking the middle mouse button instead of just two (horizontally) when using Firefox.

This issue only exists inside the "code area" of the paste and it works fine on the margin to the left for example.

Paste tried on: https://mystb.in/f0218141490c99fbbf

![firefox_P2fFGtItoR](https://github.com/PythonistaGuild/MystBin/assets/83978878/d3b881af-0486-4f53-892c-10692481ece4)

**Comment by chillymosh** [comment]
This behaviour is due to the css in `global.css` for .fileContent

If you disable overflow-x: auto and overflow-y: auto it should work in Firefox.

**Comment by EvieePy** [comment]
Not sure what you mean?
Turning `overflow-x` to `hidden` will disable to ability to see the paste, and putting it on `visble` means the paste will overflow into the main page.

**Comment by itswilliboy** [comment]
This seems to have been fixed or fixed itself, so closing.
