### ISSUE TITLE
[Backend] Basic POST/GET Pastes

### ISSUE THREAD

**Issue by IAmTomahawkx** [PythonistaGuild/MystBin#6]
Create a basic API for the frontend, and 3rd party clients to access for creating and fetching pastes

**Comment by EvieePy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Basic GET/POST Pastes](https://trello.com/c/rNr8tgCi/16-basic-get-post-pastes)

**Comment by IAmTomahawkx** [comment]
done
